# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-View
version:      0.06
version_from: lib/Class/DBI/View.pm
installdirs:  site
requires:
    Class::DBI:                    0.94
    Test::More:                    0.32
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
